base_url = "https://rdmsr.github.io"
title = "RDMSR"
compile_sass = false
generate_feeds = true

[extra]
author = "rdmsr"

[markdown]
highlighting.style = "class"
highlighting.theme = "vitesse-light"
bottom_footnotes = true

[[extra.projects]]
title = "zag"
meta = 'Software'
url = "https://github.com/rdmsr/zag"
description = "Operating system kernel"

[[extra.projects]]
title = "duck"
meta = 'Software'
url = "https://github.com/rdmsr/duck"
description = "Modern documentation generator for C and C++"
